services:
  web:
    build: ./nginx/
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8081:80"
    depends_on:
      - db
      - php

  db:
    build: ./mysql/
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  php:
    build: ./php/
    image: php:8.2
    container_name: php-container  
    expose:  
    - 9000
    volumes:
    - ./www/html/:/var/www/html/
    depends_on:
      - db

volumes:
  db_data:
    external: true
